#!/usr/bin/env ansible-playbook
---
- name: create machines
  hosts: localhost
  gather_facts: no

  tasks:
    - name: apply terraform code
      terraform:
        project_path: ./terraform
        state: present
        force_init: yes
      register: terraform

    - name: add terraform hosts to inventory
      add_host:
        name: "{{ terraform.outputs.name.value }}"

    - name: wait a moment to allow dns updates
      pause:
        seconds: 15

- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.epel
    - role: robertdebock.buildtools
    - role: robertdebock.python_pip
    - role: robertdebock.openssl
    - role: robertdebock.httpd

  post_tasks:
    - name: place an index.hyml
      copy:
        content: "Hello from {{ ansible_fqdn }}"
        dest: /var/www/html/index.html
        mode: "0644"
